#!/bin/sh
sudo apt update
sudo apt upgrade -y
sudo apt install -y \
    software-properties-common \
    iputils-ping net-tools build-essential \
    docker docker-compose \
    apache2 nginx \
    vim nodejs npm vite python3 ruby php-fpm \
    mariadb-server postgresql postgres-contrib sqlite3 \
    php-mysql php-pgsql php-sqlite3 php-curl 
sudo service apache2 start
