#!/bin/sh
. /etc/os-release

if [ "$ID" = "ubuntu" ];then
apt update
apt -y upgrade
ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
DEBIAN_FRONTEND=noninteractive apt install -y task-lxde-desktop task-japanese locales-all
#apt -y install language-pack-ja
#apt -y install language-selector-common
#apt -y install $(check-language-support)
#update-locale LANG=ja_JP.UTF-8
#apt -y install fcitx-mozc
#im-config -n fcitx
fi

if [ "$ID" = "debian" ];then
apt update
apt -y upgrade
apt -y install lxde task-japanese task-japanese-desktop
dpkg-reconfigure locales
. /etc/default/locale
apt -y install fcitx-mozc dbus-x11
dpkg-reconfigure tzdata
fi

apt install -y \
    software-properties-common \
    iputils-ping net-tools build-essential \
    vim \
    chromium-browser
