#!/bin/sh
. /etc/os-release

if [ "$ID" = "ubuntu" ];then
apt update
apt -y upgrade
#apt -y install lxde
apt -y install language-pack-ja
apt -y install language-selector-common
apt -y install $(check-language-support)
update-locale LANG=ja_JP.UTF-8
apt -y install fcitx-mozc
im-config -n fcitx
dpkg-reconfigure tzdata
fi

if [ "$ID" = "debian" ];then
apt update
apt -y upgrade
apt -y install lxde task-japanese task-japanese-desktop
dpkg-reconfigure locales
. /etc/default/locale
apt -y install fcitx-mozc dbus-x11
dpkg-reconfigure tzdata
fi

if [ "$GTK_IM_MODULE" = "" ]; then
echo "
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export DefaultIMModule=fcitx" >> $HOME/.profile
fi

echo "source ~/.profile
lxsession &" > ~/.xsessionrc
